### ISSUE TITLE
Undocumented options

### ISSUE THREAD

**Issue by bew** [wez/wezterm#461]
Here are the list of undocumented options, based on this version of the config: [config/src/lib.rs@b6d85f94](https://github.com/wez/wezterm/blob/b6d85f941db2f5df389d007fb34fa18e0139a25a/config/src/lib.rs)

- [x] adjust_window_size_when_changing_font_size
- [x] allow_square_glyphs_to_overflow_width #462 
- [x] automatically_reload_config #462 
- [x] check_for_updates #462 
- [x] check_for_updates_interval_seconds #462
- [x] daemon_options
- [x] debug_key_events
- [x] enable_csi_u_key_encoding
- [ ] experimental_shape_post_processing (won't be documented I guess)
- [x] native_macos_fullscreen_mode
- [x] ~~periodic_stat_logging~~ - internal developer use
- [x] prefer_egl
- [ ] ratelimit_mux_line_prefetches_per_second
- [x] ~~resolved_palette~~ - internal cache, not user configurable
- [x] scroll_to_bottom_on_input #462
- [x] selection_word_boundary #462
- [x] show_tab_index_in_tab_bar
- [x] show_update_window #462
- [x] ssh_domains
- [x] swap_backspace_and_delete
- [x] tab_and_split_indices_are_zero_based
- [x] tls_clients
- [x] tls_servers
- [x] ~~use_local_build_for_proxy~~ - internal developer use

---
For the record, here is how I made the list:
1. copy all lines in `Config` struct ([example](https://github.com/wez/wezterm/blob/b6d85f941db2f5df389d007fb34fa18e0139a25a/config/src/lib.rs#L459-L858)) in an empty file
2. (vim) Remove all docs with `:v/pub/d`
3. (vim) Cleanup the lines with `:%norm dndwf:D`
4. (vim) Sort all options `:%sort`
5. save file to `all_options`
6. find missing docs with:

   ```sh
   while read opt; do
     rg $opt docs/config/ > /dev/null || echo $opt
   done <all_options
   ```

**Comment by bew** [comment]
The last one from that list is `ratelimit_mux_line_prefetches_per_second` just want to note that I have no idea how to document that.

I re-ran the steps, and the undocumented options are:
```
experimental_shape_post_processing
periodic_stat_logging
ratelimit_mux_line_prefetches_per_second
resolved_palette
use_local_build_for_proxy
```
I updated the first post to add them (:

**Comment by wez** [comment]
Yeah, I think we can close this: I'm likely to change `ratelimit_mux_line_prefetches_per_second` and I don't expect anyone to need to change that value in the meantime.

**Comment by bew** [comment]
So be it!
